#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="C:\\USERS\\GENERAL\\DESKTOP\\GLAD\\UPDATED DATABASE\\WEB DESIGN\\P05\\THEDATABASE\\BF.MDF")]
public partial class BFDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertCart(Cart instance);
  partial void UpdateCart(Cart instance);
  partial void DeleteCart(Cart instance);
  partial void InsertInvoice1(Invoice1 instance);
  partial void UpdateInvoice1(Invoice1 instance);
  partial void DeleteInvoice1(Invoice1 instance);
  partial void InsertInvoice2(Invoice2 instance);
  partial void UpdateInvoice2(Invoice2 instance);
  partial void DeleteInvoice2(Invoice2 instance);
  partial void InsertOffer(Offer instance);
  partial void UpdateOffer(Offer instance);
  partial void DeleteOffer(Offer instance);
  partial void InsertPet(Pet instance);
  partial void UpdatePet(Pet instance);
  partial void DeletePet(Pet instance);
  partial void InsertUser(User instance);
  partial void UpdateUser(User instance);
  partial void DeleteUser(User instance);
  partial void InsertWishlist(Wishlist instance);
  partial void UpdateWishlist(Wishlist instance);
  partial void DeleteWishlist(Wishlist instance);
  #endregion
	
	public BFDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["C__USERS_GENERAL_DESKTOP_GLAD_UPDATED_DATABASE_WEB_DESIGN_P05_THEDATABASE_BF_MDFC" +
					"onnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public BFDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public BFDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public BFDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public BFDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Cart> Carts
	{
		get
		{
			return this.GetTable<Cart>();
		}
	}
	
	public System.Data.Linq.Table<Invoice1> Invoice1s
	{
		get
		{
			return this.GetTable<Invoice1>();
		}
	}
	
	public System.Data.Linq.Table<Invoice2> Invoice2s
	{
		get
		{
			return this.GetTable<Invoice2>();
		}
	}
	
	public System.Data.Linq.Table<Offer> Offers
	{
		get
		{
			return this.GetTable<Offer>();
		}
	}
	
	public System.Data.Linq.Table<Pet> Pets
	{
		get
		{
			return this.GetTable<Pet>();
		}
	}
	
	public System.Data.Linq.Table<User> Users
	{
		get
		{
			return this.GetTable<User>();
		}
	}
	
	public System.Data.Linq.Table<Wishlist> Wishlists
	{
		get
		{
			return this.GetTable<Wishlist>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cart")]
public partial class Cart : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Pet_Id;
	
	private string _Pet_Name;
	
	private string _Pet_Type;
	
	private string _Pet_Breed;
	
	private decimal _Pet_Price;
	
	private int _Pet_Quantity;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPet_IdChanging(int value);
    partial void OnPet_IdChanged();
    partial void OnPet_NameChanging(string value);
    partial void OnPet_NameChanged();
    partial void OnPet_TypeChanging(string value);
    partial void OnPet_TypeChanged();
    partial void OnPet_BreedChanging(string value);
    partial void OnPet_BreedChanged();
    partial void OnPet_PriceChanging(decimal value);
    partial void OnPet_PriceChanged();
    partial void OnPet_QuantityChanging(int value);
    partial void OnPet_QuantityChanged();
    #endregion
	
	public Cart()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pet_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int Pet_Id
	{
		get
		{
			return this._Pet_Id;
		}
		set
		{
			if ((this._Pet_Id != value))
			{
				this.OnPet_IdChanging(value);
				this.SendPropertyChanging();
				this._Pet_Id = value;
				this.SendPropertyChanged("Pet_Id");
				this.OnPet_IdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pet_Name", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
	public string Pet_Name
	{
		get
		{
			return this._Pet_Name;
		}
		set
		{
			if ((this._Pet_Name != value))
			{
				this.OnPet_NameChanging(value);
				this.SendPropertyChanging();
				this._Pet_Name = value;
				this.SendPropertyChanged("Pet_Name");
				this.OnPet_NameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pet_Type", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
	public string Pet_Type
	{
		get
		{
			return this._Pet_Type;
		}
		set
		{
			if ((this._Pet_Type != value))
			{
				this.OnPet_TypeChanging(value);
				this.SendPropertyChanging();
				this._Pet_Type = value;
				this.SendPropertyChanged("Pet_Type");
				this.OnPet_TypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pet_Breed", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
	public string Pet_Breed
	{
		get
		{
			return this._Pet_Breed;
		}
		set
		{
			if ((this._Pet_Breed != value))
			{
				this.OnPet_BreedChanging(value);
				this.SendPropertyChanging();
				this._Pet_Breed = value;
				this.SendPropertyChanged("Pet_Breed");
				this.OnPet_BreedChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pet_Price", DbType="Decimal(18,2) NOT NULL")]
	public decimal Pet_Price
	{
		get
		{
			return this._Pet_Price;
		}
		set
		{
			if ((this._Pet_Price != value))
			{
				this.OnPet_PriceChanging(value);
				this.SendPropertyChanging();
				this._Pet_Price = value;
				this.SendPropertyChanged("Pet_Price");
				this.OnPet_PriceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pet_Quantity", DbType="Int NOT NULL")]
	public int Pet_Quantity
	{
		get
		{
			return this._Pet_Quantity;
		}
		set
		{
			if ((this._Pet_Quantity != value))
			{
				this.OnPet_QuantityChanging(value);
				this.SendPropertyChanging();
				this._Pet_Quantity = value;
				this.SendPropertyChanged("Pet_Quantity");
				this.OnPet_QuantityChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Invoice1")]
public partial class Invoice1 : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _First_name;
	
	private string _Last_name;
	
	private string _Email;
	
	private string _Phone_number;
	
	private string _UserType;
	
	private int _Pet_Id;
	
	private string _Pet_Name;
	
	private string _Pet_Type;
	
	private string _Pet_Breed;
	
	private decimal _Pet_Price;
	
	private int _Pet_Quantity;
	
	private string _Card_Number;
	
	private System.DateTime _Date;
	
	private string _Country;
	
	private string _Street_Address;
	
	private string _City;
	
	private string _Province_State;
	
	private string _ZIP_Code;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFirst_nameChanging(string value);
    partial void OnFirst_nameChanged();
    partial void OnLast_nameChanging(string value);
    partial void OnLast_nameChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnPhone_numberChanging(string value);
    partial void OnPhone_numberChanged();
    partial void OnUserTypeChanging(string value);
    partial void OnUserTypeChanged();
    partial void OnPet_IdChanging(int value);
    partial void OnPet_IdChanged();
    partial void OnPet_NameChanging(string value);
    partial void OnPet_NameChanged();
    partial void OnPet_TypeChanging(string value);
    partial void OnPet_TypeChanged();
    partial void OnPet_BreedChanging(string value);
    partial void OnPet_BreedChanged();
    partial void OnPet_PriceChanging(decimal value);
    partial void OnPet_PriceChanged();
    partial void OnPet_QuantityChanging(int value);
    partial void OnPet_QuantityChanged();
    partial void OnCard_NumberChanging(string value);
    partial void OnCard_NumberChanged();
    partial void OnDateChanging(System.DateTime value);
    partial void OnDateChanged();
    partial void OnCountryChanging(string value);
    partial void OnCountryChanged();
    partial void OnStreet_AddressChanging(string value);
    partial void OnStreet_AddressChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnProvince_StateChanging(string value);
    partial void OnProvince_StateChanged();
    partial void OnZIP_CodeChanging(string value);
    partial void OnZIP_CodeChanged();
    #endregion
	
	public Invoice1()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_First_name", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
	public string First_name
	{
		get
		{
			return this._First_name;
		}
		set
		{
			if ((this._First_name != value))
			{
				this.OnFirst_nameChanging(value);
				this.SendPropertyChanging();
				this._First_name = value;
				this.SendPropertyChanged("First_name");
				this.OnFirst_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Last_name", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
	public string Last_name
	{
		get
		{
			return this._Last_name;
		}
		set
		{
			if ((this._Last_name != value))
			{
				this.OnLast_nameChanging(value);
				this.SendPropertyChanging();
				this._Last_name = value;
				this.SendPropertyChanged("Last_name");
				this.OnLast_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone_number", DbType="VarChar(13) NOT NULL", CanBeNull=false)]
	public string Phone_number
	{
		get
		{
			return this._Phone_number;
		}
		set
		{
			if ((this._Phone_number != value))
			{
				this.OnPhone_numberChanging(value);
				this.SendPropertyChanging();
				this._Phone_number = value;
				this.SendPropertyChanged("Phone_number");
				this.OnPhone_numberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserType", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
	public string UserType
	{
		get
		{
			return this._UserType;
		}
		set
		{
			if ((this._UserType != value))
			{
				this.OnUserTypeChanging(value);
				this.SendPropertyChanging();
				this._UserType = value;
				this.SendPropertyChanged("UserType");
				this.OnUserTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pet_Id", DbType="Int NOT NULL")]
	public int Pet_Id
	{
		get
		{
			return this._Pet_Id;
		}
		set
		{
			if ((this._Pet_Id != value))
			{
				this.OnPet_IdChanging(value);
				this.SendPropertyChanging();
				this._Pet_Id = value;
				this.SendPropertyChanged("Pet_Id");
				this.OnPet_IdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pet_Name", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
	public string Pet_Name
	{
		get
		{
			return this._Pet_Name;
		}
		set
		{
			if ((this._Pet_Name != value))
			{
				this.OnPet_NameChanging(value);
				this.SendPropertyChanging();
				this._Pet_Name = value;
				this.SendPropertyChanged("Pet_Name");
				this.OnPet_NameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pet_Type", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
	public string Pet_Type
	{
		get
		{
			return this._Pet_Type;
		}
		set
		{
			if ((this._Pet_Type != value))
			{
				this.OnPet_TypeChanging(value);
				this.SendPropertyChanging();
				this._Pet_Type = value;
				this.SendPropertyChanged("Pet_Type");
				this.OnPet_TypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pet_Breed", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
	public string Pet_Breed
	{
		get
		{
			return this._Pet_Breed;
		}
		set
		{
			if ((this._Pet_Breed != value))
			{
				this.OnPet_BreedChanging(value);
				this.SendPropertyChanging();
				this._Pet_Breed = value;
				this.SendPropertyChanged("Pet_Breed");
				this.OnPet_BreedChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pet_Price", DbType="Decimal(18,2) NOT NULL")]
	public decimal Pet_Price
	{
		get
		{
			return this._Pet_Price;
		}
		set
		{
			if ((this._Pet_Price != value))
			{
				this.OnPet_PriceChanging(value);
				this.SendPropertyChanging();
				this._Pet_Price = value;
				this.SendPropertyChanged("Pet_Price");
				this.OnPet_PriceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pet_Quantity", DbType="Int NOT NULL")]
	public int Pet_Quantity
	{
		get
		{
			return this._Pet_Quantity;
		}
		set
		{
			if ((this._Pet_Quantity != value))
			{
				this.OnPet_QuantityChanging(value);
				this.SendPropertyChanging();
				this._Pet_Quantity = value;
				this.SendPropertyChanged("Pet_Quantity");
				this.OnPet_QuantityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Card_Number", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
	public string Card_Number
	{
		get
		{
			return this._Card_Number;
		}
		set
		{
			if ((this._Card_Number != value))
			{
				this.OnCard_NumberChanging(value);
				this.SendPropertyChanging();
				this._Card_Number = value;
				this.SendPropertyChanged("Card_Number");
				this.OnCard_NumberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
	public System.DateTime Date
	{
		get
		{
			return this._Date;
		}
		set
		{
			if ((this._Date != value))
			{
				this.OnDateChanging(value);
				this.SendPropertyChanging();
				this._Date = value;
				this.SendPropertyChanged("Date");
				this.OnDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Country
	{
		get
		{
			return this._Country;
		}
		set
		{
			if ((this._Country != value))
			{
				this.OnCountryChanging(value);
				this.SendPropertyChanging();
				this._Country = value;
				this.SendPropertyChanged("Country");
				this.OnCountryChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Street_Address", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string Street_Address
	{
		get
		{
			return this._Street_Address;
		}
		set
		{
			if ((this._Street_Address != value))
			{
				this.OnStreet_AddressChanging(value);
				this.SendPropertyChanging();
				this._Street_Address = value;
				this.SendPropertyChanged("Street_Address");
				this.OnStreet_AddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
	public string City
	{
		get
		{
			return this._City;
		}
		set
		{
			if ((this._City != value))
			{
				this.OnCityChanging(value);
				this.SendPropertyChanging();
				this._City = value;
				this.SendPropertyChanged("City");
				this.OnCityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Province_State", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
	public string Province_State
	{
		get
		{
			return this._Province_State;
		}
		set
		{
			if ((this._Province_State != value))
			{
				this.OnProvince_StateChanging(value);
				this.SendPropertyChanging();
				this._Province_State = value;
				this.SendPropertyChanged("Province_State");
				this.OnProvince_StateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZIP_Code", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
	public string ZIP_Code
	{
		get
		{
			return this._ZIP_Code;
		}
		set
		{
			if ((this._ZIP_Code != value))
			{
				this.OnZIP_CodeChanging(value);
				this.SendPropertyChanging();
				this._ZIP_Code = value;
				this.SendPropertyChanged("ZIP_Code");
				this.OnZIP_CodeChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Invoice2")]
public partial class Invoice2 : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _First_name;
	
	private string _Last_name;
	
	private string _Email;
	
	private string _Phone_number;
	
	private string _UserType;
	
	private int _Pet_Id;
	
	private string _Pet_Name;
	
	private string _Pet_Type;
	
	private string _Pet_Breed;
	
	private decimal _Pet_Price;
	
	private int _Pet_Quantity;
	
	private string _Card_Number;
	
	private System.DateTime _Date;
	
	private string _Country;
	
	private string _Street_Address;
	
	private string _City;
	
	private string _Province_State;
	
	private string _ZIP_Code;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFirst_nameChanging(string value);
    partial void OnFirst_nameChanged();
    partial void OnLast_nameChanging(string value);
    partial void OnLast_nameChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnPhone_numberChanging(string value);
    partial void OnPhone_numberChanged();
    partial void OnUserTypeChanging(string value);
    partial void OnUserTypeChanged();
    partial void OnPet_IdChanging(int value);
    partial void OnPet_IdChanged();
    partial void OnPet_NameChanging(string value);
    partial void OnPet_NameChanged();
    partial void OnPet_TypeChanging(string value);
    partial void OnPet_TypeChanged();
    partial void OnPet_BreedChanging(string value);
    partial void OnPet_BreedChanged();
    partial void OnPet_PriceChanging(decimal value);
    partial void OnPet_PriceChanged();
    partial void OnPet_QuantityChanging(int value);
    partial void OnPet_QuantityChanged();
    partial void OnCard_NumberChanging(string value);
    partial void OnCard_NumberChanged();
    partial void OnDateChanging(System.DateTime value);
    partial void OnDateChanged();
    partial void OnCountryChanging(string value);
    partial void OnCountryChanged();
    partial void OnStreet_AddressChanging(string value);
    partial void OnStreet_AddressChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnProvince_StateChanging(string value);
    partial void OnProvince_StateChanged();
    partial void OnZIP_CodeChanging(string value);
    partial void OnZIP_CodeChanged();
    #endregion
	
	public Invoice2()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_First_name", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
	public string First_name
	{
		get
		{
			return this._First_name;
		}
		set
		{
			if ((this._First_name != value))
			{
				this.OnFirst_nameChanging(value);
				this.SendPropertyChanging();
				this._First_name = value;
				this.SendPropertyChanged("First_name");
				this.OnFirst_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Last_name", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
	public string Last_name
	{
		get
		{
			return this._Last_name;
		}
		set
		{
			if ((this._Last_name != value))
			{
				this.OnLast_nameChanging(value);
				this.SendPropertyChanging();
				this._Last_name = value;
				this.SendPropertyChanged("Last_name");
				this.OnLast_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone_number", DbType="VarChar(13) NOT NULL", CanBeNull=false)]
	public string Phone_number
	{
		get
		{
			return this._Phone_number;
		}
		set
		{
			if ((this._Phone_number != value))
			{
				this.OnPhone_numberChanging(value);
				this.SendPropertyChanging();
				this._Phone_number = value;
				this.SendPropertyChanged("Phone_number");
				this.OnPhone_numberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserType", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
	public string UserType
	{
		get
		{
			return this._UserType;
		}
		set
		{
			if ((this._UserType != value))
			{
				this.OnUserTypeChanging(value);
				this.SendPropertyChanging();
				this._UserType = value;
				this.SendPropertyChanged("UserType");
				this.OnUserTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pet_Id", DbType="Int NOT NULL")]
	public int Pet_Id
	{
		get
		{
			return this._Pet_Id;
		}
		set
		{
			if ((this._Pet_Id != value))
			{
				this.OnPet_IdChanging(value);
				this.SendPropertyChanging();
				this._Pet_Id = value;
				this.SendPropertyChanged("Pet_Id");
				this.OnPet_IdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pet_Name", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
	public string Pet_Name
	{
		get
		{
			return this._Pet_Name;
		}
		set
		{
			if ((this._Pet_Name != value))
			{
				this.OnPet_NameChanging(value);
				this.SendPropertyChanging();
				this._Pet_Name = value;
				this.SendPropertyChanged("Pet_Name");
				this.OnPet_NameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pet_Type", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
	public string Pet_Type
	{
		get
		{
			return this._Pet_Type;
		}
		set
		{
			if ((this._Pet_Type != value))
			{
				this.OnPet_TypeChanging(value);
				this.SendPropertyChanging();
				this._Pet_Type = value;
				this.SendPropertyChanged("Pet_Type");
				this.OnPet_TypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pet_Breed", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
	public string Pet_Breed
	{
		get
		{
			return this._Pet_Breed;
		}
		set
		{
			if ((this._Pet_Breed != value))
			{
				this.OnPet_BreedChanging(value);
				this.SendPropertyChanging();
				this._Pet_Breed = value;
				this.SendPropertyChanged("Pet_Breed");
				this.OnPet_BreedChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pet_Price", DbType="Decimal(18,2) NOT NULL")]
	public decimal Pet_Price
	{
		get
		{
			return this._Pet_Price;
		}
		set
		{
			if ((this._Pet_Price != value))
			{
				this.OnPet_PriceChanging(value);
				this.SendPropertyChanging();
				this._Pet_Price = value;
				this.SendPropertyChanged("Pet_Price");
				this.OnPet_PriceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pet_Quantity", DbType="Int NOT NULL")]
	public int Pet_Quantity
	{
		get
		{
			return this._Pet_Quantity;
		}
		set
		{
			if ((this._Pet_Quantity != value))
			{
				this.OnPet_QuantityChanging(value);
				this.SendPropertyChanging();
				this._Pet_Quantity = value;
				this.SendPropertyChanged("Pet_Quantity");
				this.OnPet_QuantityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Card_Number", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
	public string Card_Number
	{
		get
		{
			return this._Card_Number;
		}
		set
		{
			if ((this._Card_Number != value))
			{
				this.OnCard_NumberChanging(value);
				this.SendPropertyChanging();
				this._Card_Number = value;
				this.SendPropertyChanged("Card_Number");
				this.OnCard_NumberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
	public System.DateTime Date
	{
		get
		{
			return this._Date;
		}
		set
		{
			if ((this._Date != value))
			{
				this.OnDateChanging(value);
				this.SendPropertyChanging();
				this._Date = value;
				this.SendPropertyChanged("Date");
				this.OnDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Country
	{
		get
		{
			return this._Country;
		}
		set
		{
			if ((this._Country != value))
			{
				this.OnCountryChanging(value);
				this.SendPropertyChanging();
				this._Country = value;
				this.SendPropertyChanged("Country");
				this.OnCountryChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Street_Address", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string Street_Address
	{
		get
		{
			return this._Street_Address;
		}
		set
		{
			if ((this._Street_Address != value))
			{
				this.OnStreet_AddressChanging(value);
				this.SendPropertyChanging();
				this._Street_Address = value;
				this.SendPropertyChanged("Street_Address");
				this.OnStreet_AddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
	public string City
	{
		get
		{
			return this._City;
		}
		set
		{
			if ((this._City != value))
			{
				this.OnCityChanging(value);
				this.SendPropertyChanging();
				this._City = value;
				this.SendPropertyChanged("City");
				this.OnCityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Province_State", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
	public string Province_State
	{
		get
		{
			return this._Province_State;
		}
		set
		{
			if ((this._Province_State != value))
			{
				this.OnProvince_StateChanging(value);
				this.SendPropertyChanging();
				this._Province_State = value;
				this.SendPropertyChanged("Province_State");
				this.OnProvince_StateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZIP_Code", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
	public string ZIP_Code
	{
		get
		{
			return this._ZIP_Code;
		}
		set
		{
			if ((this._ZIP_Code != value))
			{
				this.OnZIP_CodeChanging(value);
				this.SendPropertyChanging();
				this._ZIP_Code = value;
				this.SendPropertyChanged("ZIP_Code");
				this.OnZIP_CodeChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Offer")]
public partial class Offer : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Offer_Id;
	
	private string _Offer_Type;
	
	private string _Offer_Title;
	
	private string _Offer_Image;
	
	private string _Offer_Description;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOffer_IdChanging(int value);
    partial void OnOffer_IdChanged();
    partial void OnOffer_TypeChanging(string value);
    partial void OnOffer_TypeChanged();
    partial void OnOffer_TitleChanging(string value);
    partial void OnOffer_TitleChanged();
    partial void OnOffer_ImageChanging(string value);
    partial void OnOffer_ImageChanged();
    partial void OnOffer_DescriptionChanging(string value);
    partial void OnOffer_DescriptionChanged();
    #endregion
	
	public Offer()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Offer_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int Offer_Id
	{
		get
		{
			return this._Offer_Id;
		}
		set
		{
			if ((this._Offer_Id != value))
			{
				this.OnOffer_IdChanging(value);
				this.SendPropertyChanging();
				this._Offer_Id = value;
				this.SendPropertyChanged("Offer_Id");
				this.OnOffer_IdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Offer_Type", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
	public string Offer_Type
	{
		get
		{
			return this._Offer_Type;
		}
		set
		{
			if ((this._Offer_Type != value))
			{
				this.OnOffer_TypeChanging(value);
				this.SendPropertyChanging();
				this._Offer_Type = value;
				this.SendPropertyChanged("Offer_Type");
				this.OnOffer_TypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Offer_Title", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
	public string Offer_Title
	{
		get
		{
			return this._Offer_Title;
		}
		set
		{
			if ((this._Offer_Title != value))
			{
				this.OnOffer_TitleChanging(value);
				this.SendPropertyChanging();
				this._Offer_Title = value;
				this.SendPropertyChanged("Offer_Title");
				this.OnOffer_TitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Offer_Image", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
	public string Offer_Image
	{
		get
		{
			return this._Offer_Image;
		}
		set
		{
			if ((this._Offer_Image != value))
			{
				this.OnOffer_ImageChanging(value);
				this.SendPropertyChanging();
				this._Offer_Image = value;
				this.SendPropertyChanged("Offer_Image");
				this.OnOffer_ImageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Offer_Description", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string Offer_Description
	{
		get
		{
			return this._Offer_Description;
		}
		set
		{
			if ((this._Offer_Description != value))
			{
				this.OnOffer_DescriptionChanging(value);
				this.SendPropertyChanging();
				this._Offer_Description = value;
				this.SendPropertyChanged("Offer_Description");
				this.OnOffer_DescriptionChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pet")]
public partial class Pet : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Pet_Id;
	
	private string _Pet_Type;
	
	private string _Pet_Breed;
	
	private string _Pet_Name;
	
	private string _Pet_Image;
	
	private string _Pet_Description;
	
	private decimal _Pet_Price;
	
	private int _Pet_Quantity;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPet_IdChanging(int value);
    partial void OnPet_IdChanged();
    partial void OnPet_TypeChanging(string value);
    partial void OnPet_TypeChanged();
    partial void OnPet_BreedChanging(string value);
    partial void OnPet_BreedChanged();
    partial void OnPet_NameChanging(string value);
    partial void OnPet_NameChanged();
    partial void OnPet_ImageChanging(string value);
    partial void OnPet_ImageChanged();
    partial void OnPet_DescriptionChanging(string value);
    partial void OnPet_DescriptionChanged();
    partial void OnPet_PriceChanging(decimal value);
    partial void OnPet_PriceChanged();
    partial void OnPet_QuantityChanging(int value);
    partial void OnPet_QuantityChanged();
    #endregion
	
	public Pet()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pet_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int Pet_Id
	{
		get
		{
			return this._Pet_Id;
		}
		set
		{
			if ((this._Pet_Id != value))
			{
				this.OnPet_IdChanging(value);
				this.SendPropertyChanging();
				this._Pet_Id = value;
				this.SendPropertyChanged("Pet_Id");
				this.OnPet_IdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pet_Type", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
	public string Pet_Type
	{
		get
		{
			return this._Pet_Type;
		}
		set
		{
			if ((this._Pet_Type != value))
			{
				this.OnPet_TypeChanging(value);
				this.SendPropertyChanging();
				this._Pet_Type = value;
				this.SendPropertyChanged("Pet_Type");
				this.OnPet_TypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pet_Breed", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
	public string Pet_Breed
	{
		get
		{
			return this._Pet_Breed;
		}
		set
		{
			if ((this._Pet_Breed != value))
			{
				this.OnPet_BreedChanging(value);
				this.SendPropertyChanging();
				this._Pet_Breed = value;
				this.SendPropertyChanged("Pet_Breed");
				this.OnPet_BreedChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pet_Name", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
	public string Pet_Name
	{
		get
		{
			return this._Pet_Name;
		}
		set
		{
			if ((this._Pet_Name != value))
			{
				this.OnPet_NameChanging(value);
				this.SendPropertyChanging();
				this._Pet_Name = value;
				this.SendPropertyChanged("Pet_Name");
				this.OnPet_NameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pet_Image", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string Pet_Image
	{
		get
		{
			return this._Pet_Image;
		}
		set
		{
			if ((this._Pet_Image != value))
			{
				this.OnPet_ImageChanging(value);
				this.SendPropertyChanging();
				this._Pet_Image = value;
				this.SendPropertyChanged("Pet_Image");
				this.OnPet_ImageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pet_Description", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string Pet_Description
	{
		get
		{
			return this._Pet_Description;
		}
		set
		{
			if ((this._Pet_Description != value))
			{
				this.OnPet_DescriptionChanging(value);
				this.SendPropertyChanging();
				this._Pet_Description = value;
				this.SendPropertyChanged("Pet_Description");
				this.OnPet_DescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pet_Price", DbType="Decimal(18,2) NOT NULL")]
	public decimal Pet_Price
	{
		get
		{
			return this._Pet_Price;
		}
		set
		{
			if ((this._Pet_Price != value))
			{
				this.OnPet_PriceChanging(value);
				this.SendPropertyChanging();
				this._Pet_Price = value;
				this.SendPropertyChanged("Pet_Price");
				this.OnPet_PriceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pet_Quantity", DbType="Int NOT NULL")]
	public int Pet_Quantity
	{
		get
		{
			return this._Pet_Quantity;
		}
		set
		{
			if ((this._Pet_Quantity != value))
			{
				this.OnPet_QuantityChanging(value);
				this.SendPropertyChanging();
				this._Pet_Quantity = value;
				this.SendPropertyChanged("Pet_Quantity");
				this.OnPet_QuantityChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[User]")]
public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _First_name;
	
	private string _Last_name;
	
	private string _Email;
	
	private string _Phone_number;
	
	private string _Password;
	
	private string _Confirm_Password;
	
	private string _UserType;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFirst_nameChanging(string value);
    partial void OnFirst_nameChanged();
    partial void OnLast_nameChanging(string value);
    partial void OnLast_nameChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnPhone_numberChanging(string value);
    partial void OnPhone_numberChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnConfirm_PasswordChanging(string value);
    partial void OnConfirm_PasswordChanged();
    partial void OnUserTypeChanging(string value);
    partial void OnUserTypeChanged();
    #endregion
	
	public User()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_First_name", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
	public string First_name
	{
		get
		{
			return this._First_name;
		}
		set
		{
			if ((this._First_name != value))
			{
				this.OnFirst_nameChanging(value);
				this.SendPropertyChanging();
				this._First_name = value;
				this.SendPropertyChanged("First_name");
				this.OnFirst_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Last_name", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
	public string Last_name
	{
		get
		{
			return this._Last_name;
		}
		set
		{
			if ((this._Last_name != value))
			{
				this.OnLast_nameChanging(value);
				this.SendPropertyChanging();
				this._Last_name = value;
				this.SendPropertyChanged("Last_name");
				this.OnLast_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone_number", DbType="VarChar(13) NOT NULL", CanBeNull=false)]
	public string Phone_number
	{
		get
		{
			return this._Phone_number;
		}
		set
		{
			if ((this._Phone_number != value))
			{
				this.OnPhone_numberChanging(value);
				this.SendPropertyChanging();
				this._Phone_number = value;
				this.SendPropertyChanged("Phone_number");
				this.OnPhone_numberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string Password
	{
		get
		{
			return this._Password;
		}
		set
		{
			if ((this._Password != value))
			{
				this.OnPasswordChanging(value);
				this.SendPropertyChanging();
				this._Password = value;
				this.SendPropertyChanged("Password");
				this.OnPasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Confirm_Password", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string Confirm_Password
	{
		get
		{
			return this._Confirm_Password;
		}
		set
		{
			if ((this._Confirm_Password != value))
			{
				this.OnConfirm_PasswordChanging(value);
				this.SendPropertyChanging();
				this._Confirm_Password = value;
				this.SendPropertyChanged("Confirm_Password");
				this.OnConfirm_PasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserType", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
	public string UserType
	{
		get
		{
			return this._UserType;
		}
		set
		{
			if ((this._UserType != value))
			{
				this.OnUserTypeChanging(value);
				this.SendPropertyChanging();
				this._UserType = value;
				this.SendPropertyChanged("UserType");
				this.OnUserTypeChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Wishlist")]
public partial class Wishlist : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _Email;
	
	private int _Pet_Id;
	
	private string _Pet_Name;
	
	private string _Pet_Type;
	
	private string _Pet_Breed;
	
	private decimal _Pet_Price;
	
	private int _Pet_Quantity;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnPet_IdChanging(int value);
    partial void OnPet_IdChanged();
    partial void OnPet_NameChanging(string value);
    partial void OnPet_NameChanged();
    partial void OnPet_TypeChanging(string value);
    partial void OnPet_TypeChanged();
    partial void OnPet_BreedChanging(string value);
    partial void OnPet_BreedChanged();
    partial void OnPet_PriceChanging(decimal value);
    partial void OnPet_PriceChanged();
    partial void OnPet_QuantityChanging(int value);
    partial void OnPet_QuantityChanged();
    #endregion
	
	public Wishlist()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pet_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int Pet_Id
	{
		get
		{
			return this._Pet_Id;
		}
		set
		{
			if ((this._Pet_Id != value))
			{
				this.OnPet_IdChanging(value);
				this.SendPropertyChanging();
				this._Pet_Id = value;
				this.SendPropertyChanged("Pet_Id");
				this.OnPet_IdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pet_Name", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
	public string Pet_Name
	{
		get
		{
			return this._Pet_Name;
		}
		set
		{
			if ((this._Pet_Name != value))
			{
				this.OnPet_NameChanging(value);
				this.SendPropertyChanging();
				this._Pet_Name = value;
				this.SendPropertyChanged("Pet_Name");
				this.OnPet_NameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pet_Type", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
	public string Pet_Type
	{
		get
		{
			return this._Pet_Type;
		}
		set
		{
			if ((this._Pet_Type != value))
			{
				this.OnPet_TypeChanging(value);
				this.SendPropertyChanging();
				this._Pet_Type = value;
				this.SendPropertyChanged("Pet_Type");
				this.OnPet_TypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pet_Breed", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
	public string Pet_Breed
	{
		get
		{
			return this._Pet_Breed;
		}
		set
		{
			if ((this._Pet_Breed != value))
			{
				this.OnPet_BreedChanging(value);
				this.SendPropertyChanging();
				this._Pet_Breed = value;
				this.SendPropertyChanged("Pet_Breed");
				this.OnPet_BreedChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pet_Price", DbType="Decimal(18,2) NOT NULL")]
	public decimal Pet_Price
	{
		get
		{
			return this._Pet_Price;
		}
		set
		{
			if ((this._Pet_Price != value))
			{
				this.OnPet_PriceChanging(value);
				this.SendPropertyChanging();
				this._Pet_Price = value;
				this.SendPropertyChanged("Pet_Price");
				this.OnPet_PriceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pet_Quantity", DbType="Int NOT NULL")]
	public int Pet_Quantity
	{
		get
		{
			return this._Pet_Quantity;
		}
		set
		{
			if ((this._Pet_Quantity != value))
			{
				this.OnPet_QuantityChanging(value);
				this.SendPropertyChanging();
				this._Pet_Quantity = value;
				this.SendPropertyChanged("Pet_Quantity");
				this.OnPet_QuantityChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
